version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0
workflows:
    build:
      jobs:
        - cypress/install:
          build: 'npm run build'
        - cypress/run:
          requires:
            -cypress/install
          record: true
          parallele: true
          parallelism: 10
          group: 'all tests'
          start: 'npm start'
