version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0
workflows:
  build:
    jobs:
      appsetup:
        steps:
          -run:
            name: Install app
            command: npm install
          -run:
            name: Start app
            command: npm start

      - cypress/run
